#!/bin/bash

echo "🔄 MongoDB Data Migration Script"
echo "================================"
echo ""
echo "This script will help you migrate your local 'avanti-cms' database to MongoDB Atlas"
echo ""
echo "Prerequisites:"
echo "1. MongoDB Atlas cluster created"
echo "2. Database user with read/write permissions"
echo "3. Network access configured (0.0.0.0/0 for development)"
echo ""
echo "Steps to migrate:"
echo ""
echo "1. Export your local data:"
echo "   mongodump --db avanti-cms --out ./backup"
echo ""
echo "2. Import to Atlas (replace with your Atlas connection string):"
echo "   mongorestore --uri 'mongodb+srv://username:password@cluster.mongodb.net/avanti-cms' ./backup/avanti-cms"
echo ""
echo "3. Test the connection:"
echo "   mongosh 'mongodb+srv://username:password@cluster.mongodb.net/avanti-cms' --eval 'db.pages.find().count()'"
echo ""
echo "Run these commands manually with your actual Atlas connection string."
